# Generated by Django 4.1.7 on 2023-04-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('coursename', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('hometown', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
                ('passedoutyear', models.IntegerField()),
            ],
        ),
    ]
